# Determinant 5-2

Calculate inverse matrix by adjoint matrix

In [1]:
import numpy as np

In [2]:
def getCofactor(M, i, j):
    M1 = M[:i, :]
    M2 = M[i+1:, :]
    tempM = np.vstack((M1, M2))
    tempM1 = tempM[:, :j]
    tempM2 = tempM[:, j+1:]
    resultM = np.hstack((tempM1, tempM2))
    return (-1)**(i+j)*np.linalg.det(resultM)

In [3]:
def getAdjointMatrix(M):
    n, _ = M.shape
    adjM = np.zeros((n,n))
    for i in range(0, n):
        for j in range(0, n):
            adjM[i][j] = getCofactor(M, j, i)
    return adjM        

In [4]:
def getInverseMatrixByAdjointMatrix(M):
    return getAdjointMatrix(M)*(1/np.linalg.det(M))

In [5]:
A = np.array([[-4, 0, 2, -1, 0],
             [1, 3, -3, -1, 4],
             [2, 0, 1, 3, 0],
             [-2, 1, -3, -1, 5],
             [1, -5, 1, 0, 5]])
print("A = ", A)

invA = getInverseMatrixByAdjointMatrix(A)
print("inverse A = ", invA)

A =  [[-4  0  2 -1  0]
 [ 1  3 -3 -1  4]
 [ 2  0  1  3  0]
 [-2  1 -3 -1  5]
 [ 1 -5  1  0  5]]
inverse A =  [[-0.07321966  0.2106319  -0.03610832 -0.24573721  0.0772317 ]
 [ 0.16950853  0.26579739  0.09729188 -0.14343029 -0.06920762]
 [ 0.32397192  0.30090271  0.09127382 -0.35105316  0.11033099]
 [-0.05917753 -0.24072217  0.32698094  0.28084253 -0.08826479]
 [ 0.11935807  0.16349047  0.08625878 -0.02407222  0.09327984]]
