In [1]:
import numpy as np

In [2]:
A = np.array([[3, 1], [2, 2]])
B = np.array([[1, 1, 0], [1, 3, 1], [2, -1, 1]])
C = np.array([[1, 1, 1], [2, 2, 0], [3, 0, 0], [0, 0, 1]])

In [3]:
def gram_schmidt_process(A):
    result = []
    for basis in A.T:
        sum = np.zeros(basis.shape)
        for orthogonal_basis in result:
            sum += np.dot(basis, orthogonal_basis) * np.array(orthogonal_basis)
        result.append(((basis - sum) / np.linalg.norm(basis - sum)).tolist())
    return np.array(result).T

In [4]:
print(f'orthogonal basis of A:\n{gram_schmidt_process(A)}')
print(f'orthogonal basis of B:\n{gram_schmidt_process(B)}')
print(f'orthogonal basis of C:\n{gram_schmidt_process(C)}')

orthogonal basis of A:
[[ 0.83205029 -0.5547002 ]
 [ 0.5547002   0.83205029]]
orthogonal basis of B:
[[ 0.40824829  0.20739034 -0.88900089]
 [ 0.40824829  0.82956136  0.38100038]
 [ 0.81649658 -0.51847585  0.25400025]]
orthogonal basis of C:
[[ 2.67261242e-01  3.58568583e-01  5.96284794e-01]
 [ 5.34522484e-01  7.17137166e-01 -2.98142397e-01]
 [ 8.01783726e-01 -5.97614305e-01  2.06877846e-17]
 [ 0.00000000e+00  0.00000000e+00  7.45355992e-01]]


In [5]:
Q, R = np.linalg.qr(C)

In [6]:
print(f'QR Decomposition\n<Q>\n{Q}\n<R>\n{R}')

QR Decomposition
<Q>
[[-2.67261242e-01 -3.58568583e-01  5.96284794e-01]
 [-5.34522484e-01 -7.17137166e-01 -2.98142397e-01]
 [-8.01783726e-01  5.97614305e-01  1.66533454e-16]
 [-0.00000000e+00 -0.00000000e+00  7.45355992e-01]]
<R>
[[-3.74165739 -1.33630621 -0.26726124]
 [ 0.         -1.79284291 -0.35856858]
 [ 0.          0.          1.34164079]]
